// Overrides the ViewController.swift generated by
// `xcrun safari-web-extension-converter`. The default template silently
// swallows errors from SFSafariApplication.showPreferencesForExtension, so
// when Safari refuses the call (most commonly because the host app is not
// in /Applications) the button appears to do nothing. This version surfaces
// the error with a useful NSAlert.

import WebKit

#if os(iOS)
import UIKit
typealias PlatformViewController = UIViewController
#elseif os(macOS)
import Cocoa
import SafariServices
typealias PlatformViewController = NSViewController
#endif

#if os(macOS)
private let extensionBundleIdentifier = (Bundle.main.bundleIdentifier ?? "") + ".Extension"
#endif

class ViewController: PlatformViewController, WKNavigationDelegate, WKScriptMessageHandler {

    @IBOutlet var webView: WKWebView!

    override func viewDidLoad() {
        super.viewDidLoad()
        webView.navigationDelegate = self
#if !STORE
        webView.configuration.preferences.setValue(true, forKey: "developerExtrasEnabled")
#endif
        webView.configuration.userContentController.add(self, name: "controller")
        webView.loadFileURL(
            Bundle.main.url(forResource: "Main", withExtension: "html")!,
            allowingReadAccessTo: Bundle.main.resourceURL!
        )
    }

    func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
#if os(iOS)
        webView.evaluateJavaScript("show('ios')")
#elseif os(macOS)
        SFSafariExtensionManager.getStateOfSafariExtension(withIdentifier: extensionBundleIdentifier) { state, error in
            guard let state = state, error == nil else { return }
            DispatchQueue.main.async {
                if #available(macOS 13, *) {
                    webView.evaluateJavaScript("show('mac', \(state.isEnabled), true)")
                } else {
                    webView.evaluateJavaScript("show('mac', \(state.isEnabled), false)")
                }
            }
        }
#endif
    }

    func userContentController(_ userContentController: WKUserContentController, didReceive message: WKScriptMessage) {
#if os(macOS)
        guard let body = message.body as? String, body == "open-preferences" else { return }
        SFSafariApplication.showPreferencesForExtension(withIdentifier: extensionBundleIdentifier) { [weak self] error in
            DispatchQueue.main.async {
                if let error = error {
                    self?.presentPreferencesError(error)
                } else {
                    NSApp.terminate(nil)
                }
            }
        }
#endif
    }

#if os(macOS)
    private func presentPreferencesError(_ error: Error) {
        let appURL = Bundle.main.bundleURL
        let inApplications = appURL.path.hasPrefix("/Applications/")

        let alert = NSAlert()
        alert.alertStyle = .warning
        if inApplications {
            alert.messageText = "Couldn't open Safari Extension preferences"
            alert.informativeText = "Safari returned: \(error.localizedDescription)\n\nOpen Safari and choose Settings → Extensions to enable the extension manually."
            alert.addButton(withTitle: "OK")
            alert.runModal()
        } else {
            alert.messageText = "Move this app to your Applications folder"
            alert.informativeText = "Safari only opens extension preferences for apps installed in /Applications. Move the app there and reopen it.\n\n(\(error.localizedDescription))"
            alert.addButton(withTitle: "Reveal in Finder")
            alert.addButton(withTitle: "Cancel")
            if alert.runModal() == .alertFirstButtonReturn {
                NSWorkspace.shared.activateFileViewerSelecting([appURL])
            }
        }
    }
#endif
}
